import { generateObject } from "ai"
import { z } from "zod"
import { AI_MODEL } from "@/lib/ai/exercise-metadata"
import type { WorkoutDraft } from "./types"

// Optional natural-language polish of the rule-engine explanations.
// The rule engine is the source of truth — this only rewrites the prose.
// Always falls back to the original reasons on any error (rate limit, etc.).

const polishSchema = z.object({
  summary: z.array(z.string()).describe("3-5 short bullet points summarizing why this workout is well designed."),
  rounds: z
    .array(
      z.object({
        roomId: z.number(),
        explanation: z.string().describe("One concise sentence explaining why this exercise fits this round."),
      }),
    )
    .describe("One entry per filled round."),
})

export async function polishExplanations(draft: WorkoutDraft): Promise<WorkoutDraft> {
  const filled = draft.rounds.filter((r) => r.exercises.length > 0)
  if (filled.length === 0) return draft

  const context = {
    label: draft.label,
    score: draft.score,
    facts: draft.summary,
    rounds: filled.map((r) => ({
      roomId: r.roomId,
      dropset: r.dropset,
      boxingRound: r.isBoxingRound,
      exercises: r.exercises.map((e) => ({
        exercise: e.video.title,
        bodyPart: e.video.bodyPart,
        equipment: e.video.equipment,
        heartRate: e.heartRate,
      })),
      reasons: r.reasons,
    })),
  }

  try {
    const { object } = await generateObject({
      model: AI_MODEL,
      schema: polishSchema,
      system:
        "You are a strength & conditioning coach. You are given a workout that was generated by a deterministic rule engine, " +
        "along with the factual reasons each exercise was chosen. Rewrite the reasons as clear, encouraging, concise coaching language. " +
        "Do NOT invent facts — only rephrase what is provided. Keep each round explanation to a single sentence.",
      prompt: JSON.stringify(context),
    })

    const byRoom: Record<number, string> = {}
    for (const r of object.rounds) byRoom[r.roomId] = r.explanation

    return {
      ...draft,
      summary: object.summary.length ? object.summary : draft.summary,
      rounds: draft.rounds.map((r) =>
        byRoom[r.roomId] ? { ...r, reasons: [byRoom[r.roomId], ...r.reasons.slice(1)] } : r,
      ),
    }
  } catch (err) {
    console.warn("[v0] workout polish failed, using rule-engine text:", (err as any)?.message)
    return draft
  }
}
